version: "3"
services:
  fastapi:
    build: .
    container_name: fastapi_app
    command: uvicorn backend:app --host 0.0.0.0 --port 8000
    env_file:
      - .env
    environment:
      - DATABASE_URL
    ports:
      - "8000:8000"
    networks:
      - app-network
    depends_on:
      - postgres_db

networks:
  app-network:
    external: true # Use the existing network created by postgres compose
    name: app-network
