name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy-to-azure:
    runs-on: ubuntu-latest
    steps:
    - name: SSH and Run Commands
      uses: appleboy/ssh-action@master  #connects in Azure VM with provided parameters
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          ls