name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  deploy-to-azure:
    runs-on: ubuntu-latest
    steps:
    - name: SSH and Run Commands
      uses: appleboy/ssh-action@master  #connects in Azure VM with provided parameters
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          ls
          sudo docker ps -a
          cd ~/fast_api_tut
          git pull origin master
          
          sudo docker build -t fastapi .
          
          #stop and delete all containers curently running 
          sudo docker rm -f $(sudo docker ps -a -q)
          
          sudo docker run -d -p 8000:8000 fastapi
      